routes/web.php
<?php

use App\Http\Controllers\UrlController;
use Illuminate\Support\Facades\Route;

Route::group(['as' => 'url.'], function (){
    Route::get('/', [UrlController::class, 'create'])->name('create');
    Route::post('/store', [UrlController::class, 'store'])->name('store');
    Route::get('/{url:shortener_url}', [UrlController::class, 'redirectToOriginal'])->name('redirect');
});

app/Models/Url.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Url extends Model
{
    use HasFactory;
    protected $guarded = false;

    public function checkTransitionsUsed(): bool
    {
        return $this->max_transitions != 0 && $this->transitions >= $this->max_transitions;
    }

    public function checkTimePassed(): bool
    {
        $dateTime1 = Carbon::parse($this->created_at);
        $time2 = Carbon::parse($this->expiry);

        $dateTime1->addHours($time2->hour)->addMinutes($time2->minute);

        return Carbon::now()->diffInSeconds($dateTime1) <= 0;
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

app/Http/Controllers/UrlController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Url\StoreRequest;
use App\Models\Url;
use Illuminate\Support\Str;

class UrlController extends Controller
{
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('create_form');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request)
    {
        $url = Url::create($request->validated() + [
            'shortener_url' => Str::random(8),
        ]);

        return redirect()->route('url.create')->with('success', 'Short link generated successfully!')->with('url', route('url.redirect', $url));
    }

    /**
     * Display the specified resource.
     */
    public function redirectToOriginal(Url $url)
    {
        if($url->checkTransitionsUsed() || $url->checkTimePassed()){
            abort(404);
        }

        $url->increment('transitions');

        return redirect($url->original_url);
    }

}

resources/views/create_form.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Short Link</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css" rel="stylesheet" type="text/css"/>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.14/js/gijgo.min.js" type="text/javascript"></script>
</head>
<body>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Create Short Link</div>
                <div class="card-body">
                    @if(session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    @if(session('url'))
                        <div class="alert alert-success" role="alert">
                            {{ session('url') }}
                        </div>
                    @endif
                    <form action="{{ route('url.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="original_url">URL</label>
                            <input type="url" name="original_url" id="original_url" value="{{ old('original_url') }}"
                                   class="form-control @error('original_url') is-invalid @enderror"
                                   required>
                            @error('original_url')
                            <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="max_transitions">Max Transitions (0 = Unlimited)</label>
                            <input type="number" name="max_transitions" value="{{ old('max_transitions') ?? 0 }}"
                                   id="max_transitions" class="form-control" required>
                            @error('max_transitions')
                            <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="expiry">Expiry (Not more than 24 hours)</label>
                            <input type="text" id="expiry" placeholder="Time" name="expiry"
                                   value="{{ old('expiry') ?? '00:00' }}"
                                   class="form-control">
                            @error('expiry')
                            <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Generate Short Link</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#expiry').timepicker({
        format: 'HH:MM',
        mode: '24hr'
    });
</script>
</body>
</html>